version: '3.8'

services:
  mariadb:
    build: ./docker
    container_name: perfumeria_db
    environment:
      MYSQL_ROOT_PASSWORD: perfumeria_root
      MYSQL_DATABASE: perfumeria
      MYSQL_USER: perfumeria_user
      MYSQL_PASSWORD: perfumeria_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d/
